"use strict";

// Generated from https://bobtranslate.com/plugin/addition/language.html by scripts/update-languages.mjs.
module.exports = Object.freeze({
  "auto": "Auto",
  "zh-Hans": "Chinese (Simplified)",
  "zh-Hant": "Chinese (Traditional)",
  "yue": "Yue Chinese",
  "wyw": "Classical Chinese",
  "pysx": "Pinyin Abbreviation",
  "en": "English",
  "ja": "Japanese",
  "ko": "Korean",
  "fr": "French",
  "de": "German",
  "es": "Spanish",
  "it": "Italian",
  "ru": "Russian",
  "pt": "Portuguese",
  "pt-pt": "Portuguese (Portugal)",
  "pt-br": "Portuguese (Brazil)",
  "nl": "Dutch",
  "pl": "Polish",
  "ar": "Arabic",
  "ab": "Abkhazian",
  "ace": "Achinese",
  "acr": "Achi",
  "acu": "Achuar-Shiwiar",
  "adh": "Adhola",
  "af": "Afrikaans",
  "agr": "Aguaruna",
  "ak": "Akan",
  "ake": "Akawaio",
  "am": "Amharic",
  "amk": "Ambai",
  "amu": "Guerrero Amuzgo",
  "an": "Aragonese",
  "any": "Anyin",
  "as": "Assamese",
  "ast": "Asturian",
  "ata": "Pele-Ata",
  "ay": "Aymara",
  "az": "Azerbaijani",
  "azb": "South Azerbaijani",
  "ba": "Bashkir",
  "bal": "Baluchi",
  "bam": "Bambara",
  "bba": "Baatonum",
  "bch": "Bariai",
  "bdh": "Baka (South Sudan)",
  "bdu": "Oroko",
  "be": "Belarusian",
  "bem": "Bemba (Zambia)",
  "ber": "Berber languages",
  "bfa": "Bari",
  "bg": "Bulgarian",
  "bho": "Bhojpuri",
  "bi": "Bislama",
  "bm": "Bambara",
  "bn": "Bengali",
  "bno": "Bantoanon",
  "bnp": "Bola",
  "bo": "Tibetan",
  "bqj": "Bandial",
  "bqp": "Busa",
  "br": "Breton",
  "bs": "Bosnian",
  "bsn": "Barasana-Eduria",
  "bus": "Bokobaru",
  "byn": "Bilin",
  "byr": "Baruya",
  "ca": "Catalan",
  "cak": "Cakchiquel",
  "cas": "Tsimané",
  "cbk": "Chavacano",
  "cbl": "Bualkhaw Chin",
  "ccp": "Chakma",
  "cdf": "Chiru",
  "ceb": "Cebuano",
  "cfm": "Falam Chin",
  "ch": "Chamorro",
  "che": "Chechen",
  "chm": "Mari (Russia)",
  "chq": "Quiotepec Chinantec",
  "chr": "Cherokee",
  "cjp": "Cabécar",
  "ckb": "Central Kurdish",
  "cki": "Kaqchikel",
  "cnh": "Haka Chin",
  "cni": "Asháninka",
  "cnr": "Montenegrin",
  "co": "Corsican",
  "cop": "Coptic",
  "cpb": "Ucayali-Yurúa Ashéninka",
  "crh": "Crimean Tatar",
  "crs": "Seselwa Creole French",
  "cs": "Czech",
  "csb": "Kashubian",
  "ctd": "Tedim Chin",
  "cv": "Chuvash",
  "cy": "Welsh",
  "czt": "Zotung Chin",
  "da": "Danish",
  "dik": "Southwestern Dinka",
  "dje": "Zarma",
  "djk": "Businenge Tongo",
  "dop": "Lukpa",
  "dtp": "Central Dusun",
  "duo": "Dupaninan Agta",
  "dv": "Dhivehi",
  "dyu": "Dyula",
  "dz": "Dzongkha",
  "ee": "Ewe",
  "el": "Greek",
  "enx": "Enxet",
  "eo": "Esperanto",
  "et": "Estonian",
  "eu": "Basque",
  "fa": "Persian",
  "fi": "Finnish",
  "fil": "Filipino",
  "fj": "Fijian",
  "fo": "Faroese",
  "fur": "Friulian",
  "fuv": "Nigerian Fulfulde",
  "fvr": "Fur",
  "fy": "Frisian",
  "ga": "Irish",
  "gbi": "Galela",
  "gbo": "Northern Grebo",
  "gd": "Scots Gaelic",
  "gil": "Gilbertese",
  "gl": "Galician",
  "gn": "Guarani",
  "gnw": "Western Bolivian Guaraní",
  "gof": "Gofa",
  "gos": "Gronings",
  "gu": "Gujarati",
  "gub": "Guajajára",
  "gur": "Farefare",
  "gv": "Manx",
  "ha": "Hausa",
  "haw": "Hawaiian",
  "hbs": "Serbo-Croatian",
  "he": "Hebrew",
  "hi": "Hindi",
  "hil": "Hiligaynon",
  "hlb": "Halbi",
  "hmn": "Hmong",
  "hmo": "Hiri Motu",
  "hr": "Croatian",
  "hsb": "Upper Sorbian",
  "ht": "Haitian Creole",
  "hu": "Hungarian",
  "hui": "Huli",
  "hup": "Hupa",
  "huv": "San Mateo Del Mar Huave",
  "hwc": "Hawai'i Creole English",
  "hy": "Armenian",
  "ia": "Interlingua",
  "iba": "Iban",
  "id": "Indonesian",
  "ie": "Interlingue",
  "ifa": "Amganad Ifugao",
  "ifb": "Ayangan Ifugao",
  "ify": "Keley-I Kallahan",
  "ig": "Igbo",
  "ikk": "Ika",
  "ilo": "Iloko",
  "inh": "Ingush",
  "io": "Ido",
  "iou": "Tuma-Irumu",
  "is": "Icelandic",
  "iu": "Inuktitut",
  "izz": "Izii",
  "jac": "Jakalteko",
  "jae": "Yabem",
  "jbo": "Lojban",
  "jiv": "Shuar",
  "jmc": "Machame",
  "jv": "Javanese",
  "jw": "Javanese",
  "jy": "Georgian",
  "ka": "Georgian",
  "kab": "Kabyle",
  "kac": "Jingpho",
  "kbh": "Camsá",
  "kbo": "Keliko",
  "kdx": "Kam",
  "kek": "Kekchí",
  "keo": "Kakwa",
  "kg": "Kongo",
  "kha": "Khasi",
  "ki": "Kikuyu",
  "kj": "Kwanyama",
  "kk": "Kazakh",
  "kl": "Kalaallisut",
  "kle": "Kulung (Nepal)",
  "km": "Khmer",
  "kmr": "Northern Kurdish",
  "kn": "Kannada",
  "knj": "Western Kanjobal",
  "kpg": "Kapingamarangi",
  "kr": "Kanuri",
  "krs": "Gbaya (Sudan)",
  "ks": "Kashmiri",
  "ksd": "Kuanua",
  "ku": "Kurdish",
  "kw": "Cornish",
  "ky": "Kyrgyz",
  "kyu": "Western Kayah",
  "la": "Latin",
  "lb": "Luxembourgish",
  "lcm": "Tungag",
  "lcp": "Western Lawa",
  "lfn": "Lingua Franca Nova",
  "lg": "Ganda",
  "li": "Limburgish",
  "ln": "Lingala",
  "lnd": "Lun Bawang",
  "lo": "Lao",
  "lsi": "Lashi",
  "lt": "Lithuanian",
  "ltg": "Latgalian",
  "lu": "Luba-Katanga",
  "lv": "Latvian",
  "mad": "Madurese",
  "mah": "Marshallese",
  "mai": "Maithili",
  "mam": "Mam",
  "map": "Northern Mam",
  "mbb": "Western Bukidnon Manobo",
  "mdy": "Male (Ethiopia)",
  "me": "Montenegro",
  "meu": "Motu",
  "mfe": "Morisyen",
  "mg": "Malagasy",
  "mh": "Marshallese",
  "mhr": "Eastern Mari",
  "mi": "Maori",
  "mk": "Macedonian",
  "ml": "Malayalam",
  "mn": "Mongolian",
  "mni": "Manipuri",
  "mos": "Mossi",
  "mps": "Dadibi",
  "mr": "Marathi",
  "mrj": "Western Mari",
  "mrw": "Maranao",
  "ms": "Malay",
  "mt": "Maltese",
  "mus": "Creek",
  "muv": "Muthuvan",
  "mww": "Hmong Daw",
  "my": "Myanmar (Burmese)",
  "nb": "Norwegian-Bokmål",
  "nch": "Central Huasteca Nahuatl",
  "nd": "North Ndebele",
  "nds": "Low German",
  "ne": "Nepali",
  "ng": "Ndonga",
  "ngl": "Lomwe",
  "ngu": "Guerrero Nahuatl",
  "nhg": "Tetelcingo Nahuatl",
  "niu": "Niuean",
  "no": "Norwegian",
  "nop": "Numanggang",
  "nr": "South Ndebele",
  "nso": "Northern Sotho",
  "ntm": "Nateni",
  "nv": "Navajo",
  "ny": "Nyanja (Chichewa)",
  "nyy": "Nyakyusa-Ngonde",
  "oc": "Occitan",
  "oj": "Ojibwa",
  "ojb": "Northwestern Ojibwa",
  "om": "Oromo",
  "ond": "Lingao",
  "or": "Odia (Oriya)",
  "os": "Ossetian",
  "otq": "Querétaro Otomi",
  "pa": "Punjabi",
  "pag": "Pangasinan",
  "pap": "Papiamento",
  "pck": "Paite Chin",
  "pil": "Yom",
  "pmn": "Pam",
  "poh": "Poqomchi'",
  "pot": "Potawatomi",
  "ppk": "Uma",
  "prk": "Parauk",
  "ps": "Pashto",
  "pss": "Kaulong",
  "ptu": "Bambam",
  "qu": "Quechua",
  "quc": "K'iche'",
  "quh": "South Bolivian Quechua",
  "quw": "Tena Lowland Quichua",
  "quz": "Cusco Quechua",
  "qxr": "Cañar Highland Quichua",
  "rm": "Romansh",
  "rmn": "Balkan Romani",
  "rn": "Rundi",
  "ro": "Romanian",
  "rom": "Romany",
  "rue": "Rusyn",
  "rug": "Roviana",
  "rw": "Kinyarwanda",
  "sa": "Sanskrit",
  "sco": "Scots",
  "sd": "Sindhi",
  "se": "Northern Sami",
  "sg": "Sango",
  "shi": "Tachelhit",
  "shn": "Shan",
  "shp": "Shipibo-Conibo",
  "si": "Sinhala (Sinhalese)",
  "sid": "Sidamo",
  "sk": "Slovak",
  "sl": "Slovenian",
  "sm": "Samoan",
  "sn": "Shona",
  "so": "Somali",
  "spy": "Sabaot",
  "sq": "Albanian",
  "sr": "Serbian",
  "sr-Cyrl": "Serbian-Cyrillic",
  "sr-Latn": "Serbian-Latin",
  "ss": "Swati",
  "ssd": "Siroi",
  "ssx": "Samberigi",
  "st": "Sesotho",
  "su": "Sundanese",
  "sv": "Swedish",
  "sw": "Swahili",
  "swp": "Suau",
  "syc": "Classical Syriac",
  "syr": "Syriac",
  "szl": "Silesian",
  "ta": "Tamil",
  "tbz": "Ditammari",
  "te": "Telugu",
  "teo": "Teso",
  "tet": "Tetum",
  "tex": "Tennet",
  "tg": "Tajik",
  "th": "Thai",
  "ti": "Tigrinya",
  "tig": "Tigre",
  "tih": "Timugon Murut",
  "tk": "Turkmen",
  "tl": "Tagalog (Filipino)",
  "tlh": "Klingon",
  "tmh": "Tamashek",
  "tn": "Tswana",
  "to": "Tongan",
  "toi": "Tonga (Zambia)",
  "tpi": "Tok Pisin",
  "tpm": "Tampulma",
  "tr": "Turkish",
  "ts": "Tsonga",
  "tt": "Tatar",
  "tvl": "Tuvalu",
  "tw": "Twi",
  "ty": "Tahitian",
  "tyv": "Tuvinian",
  "udm": "Udmurt",
  "ug": "Uyghur",
  "uk": "Ukrainian",
  "umb": "Umbundu",
  "ur": "Urdu",
  "usp": "Uspanteco",
  "uz": "Uzbek",
  "ve": "Venda",
  "vi": "Vietnamese",
  "vo": "Volapük",
  "vun": "Vunjo",
  "wa": "Walloon",
  "wal": "Wolaitta",
  "war": "Waray (Philippines)",
  "wlx": "Wali (Ghana)",
  "wo": "Wolof",
  "wrs": "Waris",
  "wsk": "Waskia",
  "xal": "Kalmyk",
  "xh": "Xhosa",
  "xsm": "Kasem",
  "yi": "Yiddish",
  "yo": "Yoruba",
  "yon": "Yongkom",
  "yua": "Yucatec Maya",
  "zu": "Zulu",
  "zyb": "Yongbei Zhuang",
  "zza": "Dimili"
});
